import { SurveyQuestion } from './types';

// BFI-2-S (30 items)
export const BFI_QUESTIONS: SurveyQuestion[] = [
    { id: 1, text: "I am someone who tends to be quiet.", trait: "extraversion", reversed: true },
    { id: 2, text: "I am someone who is compassionate, has a soft heart.", trait: "agreeableness" },
    { id: 3, text: "I am someone who tends to be disorganized.", trait: "conscientiousness", reversed: true },
    { id: 4, text: "I am someone who worries a lot.", trait: "neuroticism" },
    { id: 5, text: "I am someone who is fascinated by art, music, or literature.", trait: "openness" },
    { id: 6, text: "I am someone who is dominant, acts as a leader.", trait: "extraversion" },
    { id: 7, text: "I am someone who is sometimes rude to others.", trait: "agreeableness", reversed: true },
    { id: 8, text: "I am someone who has difficulty getting started on tasks.", trait: "conscientiousness", reversed: true },
    { id: 9, text: "I am someone who tends to feel depressed, blue.", trait: "neuroticism" },
    { id: 10, text: "I am someone who has little interest in abstract ideas.", trait: "openness", reversed: true },
    { id: 11, text: "I am someone who is full of energy.", trait: "extraversion" },
    { id: 12, text: "I am someone who assumes the best about people.", trait: "agreeableness" },
    { id: 13, text: "I am someone who is reliable, can always be counted on.", trait: "conscientiousness" },
    { id: 14, text: "I am someone who is emotionally stable, not easily upset.", trait: "neuroticism", reversed: true },
    { id: 15, text: "I am someone who is original, comes up with new ideas.", trait: "openness" },
    { id: 16, text: "I am someone who is outgoing, sociable.", trait: "extraversion" },
    { id: 17, text: "I am someone who can be cold and uncaring.", trait: "agreeableness", reversed: true },
    { id: 18, text: "I am someone who keeps things neat and tidy.", trait: "conscientiousness" },
    { id: 19, text: "I am someone who is relaxed, handles stress well.", trait: "neuroticism", reversed: true },
    { id: 20, text: "I am someone who has few artistic interests.", trait: "openness", reversed: true },
    { id: 21, text: "I am someone who prefers to have others take charge.", trait: "extraversion", reversed: true },
    { id: 22, text: "I am someone who is respectful, treats others with respect.", trait: "agreeableness" },
    { id: 23, text: "I am someone who is persistent, works until the task is finished.", trait: "conscientiousness" },
    { id: 24, text: "I am someone who feels secure, comfortable with self.", trait: "neuroticism", reversed: true },
    { id: 25, text: "I am someone who is complex, a deep thinker.", trait: "openness" },
    { id: 26, text: "I am someone who is less active than other people.", trait: "extraversion", reversed: true },
    { id: 27, text: "I am someone who tends to find fault with others.", trait: "agreeableness", reversed: true },
    { id: 28, text: "I am someone who can be somewhat careless.", trait: "conscientiousness", reversed: true },
    { id: 29, text: "I am someone who is temperamental, gets emotional easily.", trait: "neuroticism" },
    { id: 30, text: "I am someone who has little creativity.", trait: "openness", reversed: true }
];

// PVQ (40 items)
export const PVQ_QUESTIONS: SurveyQuestion[] = [
    { id: 1, text: "Thinking up new ideas and being creative is important to me.", trait: "selfDirection" },
    { id: 2, text: "It is important to me to be rich.", trait: "power" },
    { id: 3, text: "I think it is important that every person in the world be treated equally.", trait: "universalism" },
    { id: 4, text: "It's very important to me to show my abilities.", trait: "achievement" },
    { id: 5, text: "It is important to me to live in secure surroundings.", trait: "security" },
    { id: 6, text: "I think it is important to do lots of different things in life.", trait: "stimulation" },
    { id: 7, text: "I believe that people should do what they're told.", trait: "conformity" },
    { id: 8, text: "It is important to me to listen to people who are different from me.", trait: "universalism" },
    { id: 9, text: "I think it's important not to ask for more than what you have.", trait: "tradition" },
    { id: 10, text: "I seek every chance I can to have fun.", trait: "hedonism" },
    { id: 11, text: "It is important to me to make my own decisions about what I do.", trait: "selfDirection" },
    { id: 12, text: "It's very important to me to help the people around me.", trait: "benevolence" },
    { id: 13, text: "Being very successful is important to me.", trait: "achievement" },
    { id: 14, text: "It is very important to me that my country be safe.", trait: "security" },
    { id: 15, text: "I like to take risks.", trait: "stimulation" },
    { id: 16, text: "It is important to me to always behave properly.", trait: "conformity" },
    { id: 17, text: "It is important to me to be in charge and tell others what to do.", trait: "power" },
    { id: 18, text: "It is important to me to be loyal to my friends.", trait: "benevolence" },
    { id: 19, text: "I strongly believe that people should care for nature.", trait: "universalism" },
    { id: 20, text: "Religious belief is important to me.", trait: "tradition" },
    { id: 21, text: "It is important to me that things be organized and clean.", trait: "security" },
    { id: 22, text: "I think it's important to be interested in things.", trait: "selfDirection" },
    { id: 23, text: "I believe all the world's people should live in harmony.", trait: "universalism" },
    { id: 24, text: "I think it is important to be ambitious.", trait: "achievement" },
    { id: 25, text: "I think it is best to do things in traditional ways.", trait: "tradition" },
    { id: 26, text: "Enjoying life's pleasures is important to me.", trait: "hedonism" },
    { id: 27, text: "It is important to me to respond to the needs of others.", trait: "benevolence" },
    { id: 28, text: "I believe I should always show respect to parents and older people.", trait: "conformity" },
    { id: 29, text: "I want everyone to be treated justly, even people I don't know.", trait: "universalism" },
    { id: 30, text: "I like surprises.", trait: "stimulation" },
    { id: 31, text: "I try hard to avoid getting sick.", trait: "security" },
    { id: 32, text: "Getting ahead in life is important to me.", trait: "achievement" },
    { id: 33, text: "Forgiving people who have hurt me is important to me.", trait: "benevolence" },
    { id: 34, text: "It is important to me to be independent.", trait: "selfDirection" },
    { id: 35, text: "Having a stable government is important to me.", trait: "security" },
    { id: 36, text: "It is important to me to be polite to other people all the time.", trait: "conformity" },
    { id: 37, text: "I really want to enjoy life.", trait: "hedonism" },
    { id: 38, text: "It is important to me to be humble and modest.", trait: "tradition" },
    { id: 39, text: "I always want to be the one who makes the decisions.", trait: "power" },
    { id: 40, text: "It is important to me to adapt to nature and to fit into it.", trait: "universalism" }
];
