import { SurveyQuestion } from './types';

// BFI-2-S (30 items)
export const BFI_QUESTIONS: SurveyQuestion[] = [
    { id: 1, text: "나는 조용한 편이다.", trait: "extraversion", reversed: true },
    { id: 2, text: "나는 동정심이 많고 마음이 따뜻하다.", trait: "agreeableness" },
    { id: 3, text: "나는 정리를 잘 못하는 편이다.", trait: "conscientiousness", reversed: true },
    { id: 4, text: "나는 걱정이 많은 편이다.", trait: "neuroticism" },
    { id: 5, text: "나는 예술, 음악, 문학에 매료되는 편이다.", trait: "openness" },
    { id: 6, text: "나는 주도적이며 리더 역할을 한다.", trait: "extraversion" },
    { id: 7, text: "나는 가끔 다른 사람들에게 무례할 때가 있다.", trait: "agreeableness", reversed: true },
    { id: 8, text: "나는 일을 시작하는 데 어려움을 겪는다.", trait: "conscientiousness", reversed: true },
    { id: 9, text: "나는 우울하거나 의기소침해질 때가 있다.", trait: "neuroticism" },
    { id: 10, text: "나는 추상적인 아이디어에 별로 관심이 없다.", trait: "openness", reversed: true },
    { id: 11, text: "나는 에너지가 넘친다.", trait: "extraversion" },
    { id: 12, text: "나는 사람들의 선의를 믿는 편이다.", trait: "agreeableness" },
    { id: 13, text: "나는 믿음직하고 의지할 수 있는 사람이다.", trait: "conscientiousness" },
    { id: 14, text: "나는 감정적으로 안정되어 있어 쉽게 동요하지 않는다.", trait: "neuroticism", reversed: true },
    { id: 15, text: "나는 독창적이며 새로운 아이디어를 잘 낸다.", trait: "openness" },
    { id: 16, text: "나는 외향적이고 사교적이다.", trait: "extraversion" },
    { id: 17, text: "나는 냉정하고 무심할 때가 있다.", trait: "agreeableness", reversed: true },
    { id: 18, text: "나는 주변을 깔끔하고 정돈되게 유지한다.", trait: "conscientiousness" },
    { id: 19, text: "나는 편안하며 스트레스를 잘 관리한다.", trait: "neuroticism", reversed: true },
    { id: 20, text: "나는 예술적인 관심사가 거의 없다.", trait: "openness", reversed: true },
    { id: 21, text: "나는 다른 사람이 주도하는 것을 선호한다.", trait: "extraversion", reversed: true },
    { id: 22, text: "나는 타인을 존중하며 예의 바르게 대한다.", trait: "agreeableness" },
    { id: 23, text: "나는 끈기가 있으며 일을 끝까지 해낸다.", trait: "conscientiousness" },
    { id: 24, text: "나는 나 자신에 대해 안정감을 느낀다.", trait: "neuroticism", reversed: true },
    { id: 25, text: "나는 생각이 깊고 복잡한 편이다.", trait: "openness" },
    { id: 26, text: "나는 다른 사람들보다 활동적이지 않다.", trait: "extraversion", reversed: true },
    { id: 27, text: "나는 타인의 흠을 잡는 경향이 있다.", trait: "agreeableness", reversed: true },
    { id: 28, text: "나는 다소 부주의할 때가 있다.", trait: "conscientiousness", reversed: true },
    { id: 29, text: "나는 기분 변화가 심하고 감정적이다.", trait: "neuroticism" },
    { id: 30, text: "나는 창의력이 별로 없다.", trait: "openness", reversed: true }
];

// PVQ (40 items)
export const PVQ_QUESTIONS: SurveyQuestion[] = [
    { id: 1, text: "새로운 아이디어를 생각해내고 창의적인 것은 내게 중요하다.", trait: "selfDirection" },
    { id: 2, text: "부자가 되는 것은 내게 중요하다.", trait: "power" },
    { id: 3, text: "세상 모든 사람이 평등하게 대우받는 것은 내게 중요하다.", trait: "universalism" },
    { id: 4, text: "내 능력을 보여주는 것은 매우 중요하다.", trait: "achievement" },
    { id: 5, text: "안전한 환경에서 사는 것은 내게 중요하다.", trait: "security" },
    { id: 6, text: "인생에서 다양한 것을 해보는 것은 내게 중요하다.", trait: "stimulation" },
    { id: 7, text: "나는 사람들이 지시받은 대로 해야 한다고 믿는다.", trait: "conformity" },
    { id: 8, text: "나와 다른 사람들의 의견을 듣는 것은 내게 중요하다.", trait: "universalism" },
    { id: 9, text: "가진 것 이상을 요구하지 않는 것은 내게 중요하다.", trait: "tradition" },
    { id: 10, text: "나는 즐거움을 느낄 수 있는 모든 기회를 찾는다.", trait: "hedonism" },
    { id: 11, text: "내가 무엇을 할지 스스로 결정하는 것은 내게 중요하다.", trait: "selfDirection" },
    { id: 12, text: "주변 사람들을 돕는 것은 내게 매우 중요하다.", trait: "benevolence" },
    { id: 13, text: "매우 성공하는 것은 내게 중요하다.", trait: "achievement" },
    { id: 14, text: "국가가 안전한 것은 내게 매우 중요하다.", trait: "security" },
    { id: 15, text: "나는 위험을 감수하는 것을 좋아한다.", trait: "stimulation" },
    { id: 16, text: "항상 올바르게 행동하는 것은 내게 중요하다.", trait: "conformity" },
    { id: 17, text: "내가 주도하고 다른 사람들에게 지시하는 것은 내게 중요하다.", trait: "power" },
    { id: 18, text: "친구들에게 의리를 지키는 것은 내게 중요하다.", trait: "benevolence" },
    { id: 19, text: "사람들이 자연을 보호해야 한다고 강하게 믿는다.", trait: "universalism" },
    { id: 20, text: "종교적 신념은 내게 중요하다.", trait: "tradition" },
    { id: 21, text: "주변이 정리되고 깨끗한 것은 내게 중요하다.", trait: "security" },
    { id: 22, text: "다양한 것에 관심을 가지는 것은 내게 중요하다.", trait: "selfDirection" },
    { id: 23, text: "나는 전 세계 사람들이 조화롭게 살아야 한다고 믿는다.", trait: "universalism" },
    { id: 24, text: "야망을 가지는 것은 내게 중요하다.", trait: "achievement" },
    { id: 25, text: "전통적인 방식대로 하는 것이 가장 좋다고 생각한다.", trait: "tradition" },
    { id: 26, text: "인생의 즐거움을 누리는 것은 내게 중요하다.", trait: "hedonism" },
    { id: 27, text: "다른 사람의 필요에 반응하는 것은 내게 중요하다.", trait: "benevolence" },
    { id: 28, text: "부모님과 어른들을 공경해야 한다고 믿는다.", trait: "conformity" },
    { id: 29, text: "나는 모르는 사람이라도 모두가 공정하게 대우받기를 원한다.", trait: "universalism" },
    { id: 30, text: "나는 놀라움(서프라이즈)을 좋아한다.", trait: "stimulation" },
    { id: 31, text: "나는 아프지 않으려고 열심히 노력한다.", trait: "security" },
    { id: 32, text: "인생에서 앞서 나가는 것은 내게 중요하다.", trait: "achievement" },
    { id: 33, text: "나에게 상처 준 사람들을 용서하는 것은 내게 중요하다.", trait: "benevolence" },
    { id: 34, text: "독립적인 것은 내게 중요하다.", trait: "selfDirection" },
    { id: 35, text: "안정적인 정부를 갖는 것은 내게 중요하다.", trait: "security" },
    { id: 36, text: "다른 사람들에게 항상 예의를 갖추는 것은 내게 중요하다.", trait: "conformity" },
    { id: 37, text: "나는 인생을 정말로 즐기고 싶다.", trait: "hedonism" },
    { id: 38, text: "겸손하고 나를 낮추는 것은 내게 중요하다.", trait: "tradition" },
    { id: 39, text: "나는 언제나 결정하는 사람이 되고 싶다.", trait: "power" },
    { id: 40, text: "자연에 적응하고 조화를 이루는 것은 내게 중요하다.", trait: "universalism" }
];
